### ISSUE TITLE
Issue "net::ERR_NAME_NOT_RESOLVED" happens

### ISSUE THREAD

**Issue by Granddevv** [StevenCreates/react-file-aws#8]
HI @StevenCreates 

When I tried to uploading, I got  an issue like "net::ERR_NAME_NOT_RESOLVED"

react-aws-s3.js:1 POST https://{BUCKET_NAME}.s3-{REGION}.amazonaws.com/

I already updated the bucket CORS configuration, but not sure why this happens.

**Comment by StevenCreates** [comment]
@Granddevv I haven't seen this error before, I'll try and recreate it though. 
From first glance it makes me feel like you don't have your .env variables set up.
Do you have those values set there?

**Comment by Granddevv** [comment]
I already set the whole env variables in .env file

**Comment by Granddevv** [comment]
@StevenCreates Did you set any permissions on s3 bucket?

**Comment by ashah97** [comment]
> @StevenCreates Did you set any permissions on s3 bucket?

Hello, Do you have solved the issue  "net::ERR_NAME_NOT_RESOLVED" as I'm also getting the same error.

**Comment by StevenCreates** [comment]
@Granddevv  and @ashah97 
If you google this error its a common issue with aws s3

https://stackoverflow.com/questions/63446274/neterr-name-not-resolved-error-when-sending-picture-to-aws-s3-bucket
https://medium.com/serverlessguru/err-name-not-resolved-aws-route-53-abb88c43e884

Its either going to be your config or your cors policy on aws s3
